/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AggCompositeTerm model module.
 * @module model/AggCompositeTerm
 * @version 8.2.0
 */
class AggCompositeTerm {
    /**
     * Constructs a new <code>AggCompositeTerm</code>.
     * Object representing a term to be used in composite aggregation.
     * @alias module:model/AggCompositeTerm
     * @param field {String} Name of field to operate with
     */
    constructor(field) { 
        
        AggCompositeTerm.initialize(this, field);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, field) { 
        obj['field'] = field;
    }

    /**
     * Constructs a <code>AggCompositeTerm</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AggCompositeTerm} obj Optional instance to populate.
     * @return {module:model/AggCompositeTerm} The populated <code>AggCompositeTerm</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AggCompositeTerm();

            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AggCompositeTerm</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AggCompositeTerm</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AggCompositeTerm.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['field'] && !(typeof data['field'] === 'string' || data['field'] instanceof String)) {
            throw new Error("Expected the field `field` to be a primitive type in the JSON string but got " + data['field']);
        }

        return true;
    }


}

AggCompositeTerm.RequiredProperties = ["field"];

/**
 * Name of field to operate with
 * @member {String} field
 */
AggCompositeTerm.prototype['field'] = undefined;






export default AggCompositeTerm;

