/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BulkResponse model module.
 * @module model/BulkResponse
 * @version 8.0.0
 */
class BulkResponse {
    /**
     * Constructs a new <code>BulkResponse</code>.
     * Success response for bulk search requests
     * @alias module:model/BulkResponse
     */
    constructor() { 
        
        BulkResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BulkResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BulkResponse} obj Optional instance to populate.
     * @return {module:model/BulkResponse} The populated <code>BulkResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BulkResponse();

            if (data.hasOwnProperty('items')) {
                obj['items'] = ApiClient.convertToType(data['items'], [Object]);
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], 'Boolean');
            }
            if (data.hasOwnProperty('error')) {
                obj['error'] = ApiClient.convertToType(data['error'], 'String');
            }
            if (data.hasOwnProperty('current_line')) {
                obj['current_line'] = ApiClient.convertToType(data['current_line'], 'Number');
            }
            if (data.hasOwnProperty('skipped_lines')) {
                obj['skipped_lines'] = ApiClient.convertToType(data['skipped_lines'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BulkResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BulkResponse</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['items'])) {
            throw new Error("Expected the field `items` to be an array in the JSON data but got " + data['items']);
        }
        // ensure the json data is a string
        if (data['error'] && !(typeof data['error'] === 'string' || data['error'] instanceof String)) {
            throw new Error("Expected the field `error` to be a primitive type in the JSON string but got " + data['error']);
        }

        return true;
    }


}



/**
 * List of results
 * @member {Array.<Object>} items
 */
BulkResponse.prototype['items'] = undefined;

/**
 * Errors occurred during the bulk operation
 * @member {Boolean} errors
 */
BulkResponse.prototype['errors'] = undefined;

/**
 * Error message describing an error if such occurred
 * @member {String} error
 */
BulkResponse.prototype['error'] = undefined;

/**
 * Number of the row returned in the response
 * @member {Number} current_line
 */
BulkResponse.prototype['current_line'] = undefined;

/**
 * Number of rows skipped in the response
 * @member {Number} skipped_lines
 */
BulkResponse.prototype['skipped_lines'] = undefined;






export default BulkResponse;

