/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HighlightFieldOption model module.
 * @module model/HighlightFieldOption
 * @version 8.0.0
 */
class HighlightFieldOption {
    /**
     * Constructs a new <code>HighlightFieldOption</code>.
     * Options for controlling the behavior of highlighting on a per-field basis
     * @alias module:model/HighlightFieldOption
     */
    constructor() { 
        
        HighlightFieldOption.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HighlightFieldOption</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HighlightFieldOption} obj Optional instance to populate.
     * @return {module:model/HighlightFieldOption} The populated <code>HighlightFieldOption</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HighlightFieldOption();

            if (data.hasOwnProperty('fragment_size')) {
                obj['fragment_size'] = ApiClient.convertToType(data['fragment_size'], 'Number');
            }
            if (data.hasOwnProperty('limit')) {
                obj['limit'] = ApiClient.convertToType(data['limit'], 'Number');
            }
            if (data.hasOwnProperty('limit_snippets')) {
                obj['limit_snippets'] = ApiClient.convertToType(data['limit_snippets'], 'Number');
            }
            if (data.hasOwnProperty('limit_words')) {
                obj['limit_words'] = ApiClient.convertToType(data['limit_words'], 'Number');
            }
            if (data.hasOwnProperty('number_of_fragments')) {
                obj['number_of_fragments'] = ApiClient.convertToType(data['number_of_fragments'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HighlightFieldOption</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HighlightFieldOption</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * Maximum size of the text fragments in highlighted snippets per field
 * @member {Number} fragment_size
 */
HighlightFieldOption.prototype['fragment_size'] = undefined;

/**
 * Maximum size of snippets per field
 * @member {Number} limit
 */
HighlightFieldOption.prototype['limit'] = undefined;

/**
 * Maximum number of snippets per field
 * @member {Number} limit_snippets
 */
HighlightFieldOption.prototype['limit_snippets'] = undefined;

/**
 * Maximum number of words per field
 * @member {Number} limit_words
 */
HighlightFieldOption.prototype['limit_words'] = undefined;

/**
 * Total number of highlighted fragments per field
 * @member {Number} number_of_fragments
 */
HighlightFieldOption.prototype['number_of_fragments'] = undefined;






export default HighlightFieldOption;

