/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HighlightFields model module.
 * @module model/HighlightFields
 * @version 9.0.0
 */
class HighlightFields {
    /**
     * Constructs a new <code>HighlightFields</code>.
     * List of fields available for highlighting
     * @alias module:model/HighlightFields
     * @param {(module:model/Object|module:model/[String])} instance The actual instance to initialize HighlightFields.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            // validate array data type
            if (!Array.isArray(instance)) {
                throw new Error("Invalid data type. Expecting array. Input: " + instance);
            }
            // validate array of string
            for (const item of instance) {
                if (!(typeof item === 'number' && item % 1 === 0)) {
                    throw new Error("Invalid array items. Must be string. Input: " + instance);
                }
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into [String]
            errorMessages.push("Failed to construct [String]: " + err)
        }

        try {
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Object
            errorMessages.push("Failed to construct Object: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `HighlightFields` with oneOf schemas Object, [String]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `HighlightFields` with oneOf schemas Object, [String]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>HighlightFields</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HighlightFields} obj Optional instance to populate.
     * @return {module:model/HighlightFields} The populated <code>HighlightFields</code> instance.
     */
    static constructFromObject(data, obj) {
        return new HighlightFields(data);
    }

    /**
     * Gets the actual instance, which can be <code>Object</code>, <code>[String]</code>.
     * @return {(module:model/Object|module:model/[String])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>Object</code>, <code>[String]</code>.
     * @param {(module:model/Object|module:model/[String])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = HighlightFields.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of HighlightFields from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/HighlightFields} An instance of HighlightFields.
     */
    static fromJSON = function(json_string){
        return HighlightFields.constructFromObject(JSON.parse(json_string));
    }
}


HighlightFields.OneOf = ["Object", "[String]"];

export default HighlightFields;
