/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HitsHits model module.
 * @module model/HitsHits
 * @version 7.0.0
 */
class HitsHits {
    /**
     * Constructs a new <code>HitsHits</code>.
     * Search hit representing a matched document
     * @alias module:model/HitsHits
     */
    constructor() { 
        
        HitsHits.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>HitsHits</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HitsHits} obj Optional instance to populate.
     * @return {module:model/HitsHits} The populated <code>HitsHits</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HitsHits();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'Number');
            }
            if (data.hasOwnProperty('_score')) {
                obj['_score'] = ApiClient.convertToType(data['_score'], 'Number');
            }
            if (data.hasOwnProperty('_source')) {
                obj['_source'] = ApiClient.convertToType(data['_source'], Object);
            }
            if (data.hasOwnProperty('_knn_dist')) {
                obj['_knn_dist'] = ApiClient.convertToType(data['_knn_dist'], 'Number');
            }
            if (data.hasOwnProperty('highlight')) {
                obj['highlight'] = ApiClient.convertToType(data['highlight'], Object);
            }
            if (data.hasOwnProperty('table')) {
                obj['table'] = ApiClient.convertToType(data['table'], 'String');
            }
            if (data.hasOwnProperty('_type:')) {
                obj['_type:'] = ApiClient.convertToType(data['_type:'], 'String');
            }
            if (data.hasOwnProperty('fields')) {
                obj['fields'] = ApiClient.convertToType(data['fields'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HitsHits</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HitsHits</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['table'] && !(typeof data['table'] === 'string' || data['table'] instanceof String)) {
            throw new Error("Expected the field `table` to be a primitive type in the JSON string but got " + data['table']);
        }
        // ensure the json data is a string
        if (data['_type:'] && !(typeof data['_type:'] === 'string' || data['_type:'] instanceof String)) {
            throw new Error("Expected the field `_type:` to be a primitive type in the JSON string but got " + data['_type:']);
        }

        return true;
    }


}



/**
 * The ID of the matched document
 * @member {Number} _id
 */
HitsHits.prototype['_id'] = undefined;

/**
 * The score of the matched document
 * @member {Number} _score
 */
HitsHits.prototype['_score'] = undefined;

/**
 * The source data of the matched document
 * @member {Object} _source
 */
HitsHits.prototype['_source'] = undefined;

/**
 * The knn distance of the matched document returned for knn queries
 * @member {Number} _knn_dist
 */
HitsHits.prototype['_knn_dist'] = undefined;

/**
 * The highlighting-related data of the matched document
 * @member {Object} highlight
 */
HitsHits.prototype['highlight'] = undefined;

/**
 * The table name of the matched document returned for percolate queries
 * @member {String} table
 */
HitsHits.prototype['table'] = undefined;

/**
 * The type of the matched document returned for percolate queries
 * @member {String} _type:
 */
HitsHits.prototype['_type:'] = undefined;

/**
 * The percolate-related fields of the matched document returned for percolate queries
 * @member {Object} fields
 */
HitsHits.prototype['fields'] = undefined;






export default HitsHits;

