/**
 * Manticore Search Client
 * Please note that this client is experimental. For full documentation of the API methods consult https://manual.manticoresearch.com/. 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 5.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Manticoresearch) {
      root.Manticoresearch = {};
    }
    root.Manticoresearch.InsertDocumentRequest = factory(root.Manticoresearch.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The InsertDocumentRequest model module.
   * @module model/InsertDocumentRequest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>InsertDocumentRequest</code>.
   * Object with document data. 
   * @alias module:model/InsertDocumentRequest
   * @class
   * @param index {String} Name of the index
   * @param doc {Object.<String, Object>} Object with document data 
   */
  var exports = function(index, doc) {
    var _this = this;

    _this['index'] = index;
    _this['doc'] = doc;
  };

  /**
   * Constructs a <code>InsertDocumentRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InsertDocumentRequest} obj Optional instance to populate.
   * @return {module:model/InsertDocumentRequest} The populated <code>InsertDocumentRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('index')) {
        obj['index'] = ApiClient.convertToType(data['index'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Number');
      }
      if (data.hasOwnProperty('doc')) {
        obj['doc'] = ApiClient.convertToType(data['doc'], {'String': Object});
      }
    }
    return obj;
  }

  /**
   * Name of the index
   * @member {String} index
   */
  exports.prototype['index'] = undefined;
  /**
   * Document ID. 
   * @member {Number} id
   */
  exports.prototype['id'] = undefined;
  /**
   * Object with document data 
   * @member {Object.<String, Object>} doc
   */
  exports.prototype['doc'] = undefined;



  return exports;
}));


