/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InsertDocumentRequest model module.
 * @module model/InsertDocumentRequest
 * @version 8.0.0
 */
class InsertDocumentRequest {
    /**
     * Constructs a new <code>InsertDocumentRequest</code>.
     * Object containing data for inserting a new document into the table 
     * @alias module:model/InsertDocumentRequest
     * @param table {String} Name of the table to insert the document into
     * @param doc {Object} Object containing document data 
     */
    constructor(table, doc) { 
        
        InsertDocumentRequest.initialize(this, table, doc);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, table, doc) { 
        obj['table'] = table;
        obj['doc'] = doc;
    }

    /**
     * Constructs a <code>InsertDocumentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InsertDocumentRequest} obj Optional instance to populate.
     * @return {module:model/InsertDocumentRequest} The populated <code>InsertDocumentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InsertDocumentRequest();

            if (data.hasOwnProperty('table')) {
                obj['table'] = ApiClient.convertToType(data['table'], 'String');
            }
            if (data.hasOwnProperty('cluster')) {
                obj['cluster'] = ApiClient.convertToType(data['cluster'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('doc')) {
                obj['doc'] = ApiClient.convertToType(data['doc'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InsertDocumentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InsertDocumentRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InsertDocumentRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['table'] && !(typeof data['table'] === 'string' || data['table'] instanceof String)) {
            throw new Error("Expected the field `table` to be a primitive type in the JSON string but got " + data['table']);
        }
        // ensure the json data is a string
        if (data['cluster'] && !(typeof data['cluster'] === 'string' || data['cluster'] instanceof String)) {
            throw new Error("Expected the field `cluster` to be a primitive type in the JSON string but got " + data['cluster']);
        }

        return true;
    }


}

InsertDocumentRequest.RequiredProperties = ["table", "doc"];

/**
 * Name of the table to insert the document into
 * @member {String} table
 */
InsertDocumentRequest.prototype['table'] = undefined;

/**
 * Name of the cluster to insert the document into
 * @member {String} cluster
 */
InsertDocumentRequest.prototype['cluster'] = undefined;

/**
 * Document ID. If not provided, an ID will be auto-generated 
 * @member {Number} id
 */
InsertDocumentRequest.prototype['id'] = undefined;

/**
 * Object containing document data 
 * @member {Object} doc
 */
InsertDocumentRequest.prototype['doc'] = undefined;






export default InsertDocumentRequest;

