/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import FulltextFilter from './FulltextFilter';

/**
 * The JoinCond model module.
 * @module model/JoinCond
 * @version 10.0.0
 */
class JoinCond {
    /**
     * Constructs a new <code>JoinCond</code>.
     * Object representing the conditions used to perform the join operation
     * @alias module:model/JoinCond
     * @param field {String} Field to join on
     * @param table {String} Joined table
     */
    constructor(field, table) { 
        
        JoinCond.initialize(this, field, table);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, field, table) { 
        obj['field'] = field;
        obj['table'] = table;
    }

    /**
     * Constructs a <code>JoinCond</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JoinCond} obj Optional instance to populate.
     * @return {module:model/JoinCond} The populated <code>JoinCond</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JoinCond();

            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('table')) {
                obj['table'] = ApiClient.convertToType(data['table'], 'String');
            }
            if (data.hasOwnProperty('query')) {
                obj['query'] = FulltextFilter.constructFromObject(data['query']);
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JoinCond</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JoinCond</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of JoinCond.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['field'] && !(typeof data['field'] === 'string' || data['field'] instanceof String)) {
            throw new Error("Expected the field `field` to be a primitive type in the JSON string but got " + data['field']);
        }
        // ensure the json data is a string
        if (data['table'] && !(typeof data['table'] === 'string' || data['table'] instanceof String)) {
            throw new Error("Expected the field `table` to be a primitive type in the JSON string but got " + data['table']);
        }
        // validate the optional field `query`
        if (data['query']) { // data not null
          FulltextFilter.validateJSON(data['query']);
        }

        return true;
    }


}

JoinCond.RequiredProperties = ["field", "table"];

/**
 * Field to join on
 * @member {String} field
 */
JoinCond.prototype['field'] = undefined;

/**
 * Joined table
 * @member {String} table
 */
JoinCond.prototype['table'] = undefined;

/**
 * @member {module:model/FulltextFilter} query
 */
JoinCond.prototype['query'] = undefined;

/**
 * @member {Object} type
 */
JoinCond.prototype['type'] = undefined;






export default JoinCond;
