/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import JoinCond from './JoinCond';

/**
 * The JoinOn model module.
 * @module model/JoinOn
 * @version 9.0.0
 */
class JoinOn {
    /**
     * Constructs a new <code>JoinOn</code>.
     * @alias module:model/JoinOn
     */
    constructor() { 
        
        JoinOn.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>JoinOn</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JoinOn} obj Optional instance to populate.
     * @return {module:model/JoinOn} The populated <code>JoinOn</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JoinOn();

            if (data.hasOwnProperty('right')) {
                obj['right'] = JoinCond.constructFromObject(data['right']);
            }
            if (data.hasOwnProperty('left')) {
                obj['left'] = JoinCond.constructFromObject(data['left']);
            }
            if (data.hasOwnProperty('operator')) {
                obj['operator'] = ApiClient.convertToType(data['operator'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JoinOn</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JoinOn</code>.
     */
    static validateJSON(data) {
        // validate the optional field `right`
        if (data['right']) { // data not null
          JoinCond.validateJSON(data['right']);
        }
        // validate the optional field `left`
        if (data['left']) { // data not null
          JoinCond.validateJSON(data['left']);
        }
        // ensure the json data is a string
        if (data['operator'] && !(typeof data['operator'] === 'string' || data['operator'] instanceof String)) {
            throw new Error("Expected the field `operator` to be a primitive type in the JSON string but got " + data['operator']);
        }

        return true;
    }


}



/**
 * @member {module:model/JoinCond} right
 */
JoinOn.prototype['right'] = undefined;

/**
 * @member {module:model/JoinCond} left
 */
JoinOn.prototype['left'] = undefined;

/**
 * @member {module:model/JoinOn.OperatorEnum} operator
 */
JoinOn.prototype['operator'] = undefined;





/**
 * Allowed values for the <code>operator</code> property.
 * @enum {String}
 * @readonly
 */
JoinOn['OperatorEnum'] = {

    /**
     * value: "eq"
     * @const
     */
    "eq": "eq"
};


export default JoinOn;
