/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import QueryFilter from './QueryFilter';

/**
 * The KnnQuery model module.
 * @module model/KnnQuery
 * @version 6.0.0
 */
class KnnQuery {
    /**
     * Constructs a new <code>KnnQuery</code>.
     * Object representing a k-nearest neighbor search query
     * @alias module:model/KnnQuery
     * @param field {String} Field to perform the k-nearest neighbor search on
     * @param k {Number} The number of nearest neighbors to return
     */
    constructor(field, k) { 
        
        KnnQuery.initialize(this, field, k);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, field, k) { 
        obj['field'] = field;
        obj['k'] = k;
    }

    /**
     * Constructs a <code>KnnQuery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KnnQuery} obj Optional instance to populate.
     * @return {module:model/KnnQuery} The populated <code>KnnQuery</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KnnQuery();

            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('k')) {
                obj['k'] = ApiClient.convertToType(data['k'], 'Number');
            }
            if (data.hasOwnProperty('query_vector')) {
                obj['query_vector'] = ApiClient.convertToType(data['query_vector'], ['Number']);
            }
            if (data.hasOwnProperty('doc_id')) {
                obj['doc_id'] = ApiClient.convertToType(data['doc_id'], 'Number');
            }
            if (data.hasOwnProperty('ef')) {
                obj['ef'] = ApiClient.convertToType(data['ef'], 'Number');
            }
            if (data.hasOwnProperty('filter')) {
                obj['filter'] = QueryFilter.constructFromObject(data['filter']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>KnnQuery</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>KnnQuery</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of KnnQuery.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['field'] && !(typeof data['field'] === 'string' || data['field'] instanceof String)) {
            throw new Error("Expected the field `field` to be a primitive type in the JSON string but got " + data['field']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['query_vector'])) {
            throw new Error("Expected the field `query_vector` to be an array in the JSON data but got " + data['query_vector']);
        }
        // validate the optional field `filter`
        if (data['filter']) { // data not null
          QueryFilter.validateJSON(data['filter']);
        }

        return true;
    }


}

KnnQuery.RequiredProperties = ["field", "k"];

/**
 * Field to perform the k-nearest neighbor search on
 * @member {String} field
 */
KnnQuery.prototype['field'] = undefined;

/**
 * The number of nearest neighbors to return
 * @member {Number} k
 */
KnnQuery.prototype['k'] = undefined;

/**
 * The vector used as input for the KNN search
 * @member {Array.<Number>} query_vector
 */
KnnQuery.prototype['query_vector'] = undefined;

/**
 * The docuemnt ID used as input for the KNN search
 * @member {Number} doc_id
 */
KnnQuery.prototype['doc_id'] = undefined;

/**
 * Optional parameter controlling the accuracy of the search
 * @member {Number} ef
 */
KnnQuery.prototype['ef'] = undefined;

/**
 * @member {module:model/QueryFilter} filter
 */
KnnQuery.prototype['filter'] = undefined;






export default KnnQuery;

