/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The KnnQuery model module.
 * @module model/KnnQuery
 * @version 9.0.0
 */
class KnnQuery {
    /**
     * Constructs a new <code>KnnQuery</code>.
     * @alias module:model/KnnQuery
     * @param {(module:model/String|module:model/[Number])} instance The actual instance to initialize KnnQuery.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        try {
            // validate array data type
            if (!Array.isArray(instance)) {
                throw new Error("Invalid data type. Expecting array. Input: " + instance);
            }
            // validate array of number
            for (const item of instance) {
                if (!(typeof instance === 'number' && instance % 1 != 0)) {
                    throw new Error("Invalid array items. Must be number. Input: " + JSON.stringify(instance));
                }
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into [Number]
            errorMessages.push("Failed to construct [Number]: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `KnnQuery` with oneOf schemas String, [Number]. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `KnnQuery` with oneOf schemas String, [Number]. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>KnnQuery</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KnnQuery} obj Optional instance to populate.
     * @return {module:model/KnnQuery} The populated <code>KnnQuery</code> instance.
     */
    static constructFromObject(data, obj) {
        return new KnnQuery(data);
    }

    /**
     * Gets the actual instance, which can be <code>String</code>, <code>[Number]</code>.
     * @return {(module:model/String|module:model/[Number])} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>String</code>, <code>[Number]</code>.
     * @param {(module:model/String|module:model/[Number])} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = KnnQuery.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of KnnQuery from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/KnnQuery} An instance of KnnQuery.
     */
    static fromJSON = function(json_string){
        return KnnQuery.constructFromObject(JSON.parse(json_string));
    }
}


KnnQuery.OneOf = ["String", "[Number]"];

export default KnnQuery;
