/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PercolateRequestQuery from './PercolateRequestQuery';

/**
 * The PercolateRequest model module.
 * @module model/PercolateRequest
 * @version 9.0.0
 */
class PercolateRequest {
    /**
     * Constructs a new <code>PercolateRequest</code>.
     * Object containing the query for percolating documents against stored queries in a percolate table
     * @alias module:model/PercolateRequest
     * @param query {module:model/PercolateRequestQuery} 
     */
    constructor(query) { 
        
        PercolateRequest.initialize(this, query);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, query) { 
        obj['query'] = query;
    }

    /**
     * Constructs a <code>PercolateRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PercolateRequest} obj Optional instance to populate.
     * @return {module:model/PercolateRequest} The populated <code>PercolateRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PercolateRequest();

            if (data.hasOwnProperty('query')) {
                obj['query'] = PercolateRequestQuery.constructFromObject(data['query']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PercolateRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PercolateRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PercolateRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `query`
        if (data['query']) { // data not null
          PercolateRequestQuery.validateJSON(data['query']);
        }

        return true;
    }


}

PercolateRequest.RequiredProperties = ["query"];

/**
 * @member {module:model/PercolateRequestQuery} query
 */
PercolateRequest.prototype['query'] = undefined;






export default PercolateRequest;
