/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ResponseErrorDetails from './ResponseErrorDetails';

/**
 * The ResponseError model module.
 * @module model/ResponseError
 * @version 5.0.0
 */
class ResponseError {
    /**
     * Constructs a new <code>ResponseError</code>.
     * @alias module:model/ResponseError
     * @param {(module:model/ResponseErrorDetails|module:model/String)} instance The actual instance to initialize ResponseError.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "ResponseErrorDetails") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                ResponseErrorDetails.validateJSON(instance); // throw an exception if no match
                // create ResponseErrorDetails from JS object
                this.actualInstance = ResponseErrorDetails.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into ResponseErrorDetails
            errorMessages.push("Failed to construct ResponseErrorDetails: " + err)
        }

        // Error message text returned in case of an error
        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `ResponseError` with oneOf schemas ResponseErrorDetails, String. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `ResponseError` with oneOf schemas ResponseErrorDetails, String. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>ResponseError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ResponseError} obj Optional instance to populate.
     * @return {module:model/ResponseError} The populated <code>ResponseError</code> instance.
     */
    static constructFromObject(data, obj) {
        return new ResponseError(data);
    }

    /**
     * Gets the actual instance, which can be <code>ResponseErrorDetails</code>, <code>String</code>.
     * @return {(module:model/ResponseErrorDetails|module:model/String)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>ResponseErrorDetails</code>, <code>String</code>.
     * @param {(module:model/ResponseErrorDetails|module:model/String)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = ResponseError.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of ResponseError from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/ResponseError} An instance of ResponseError.
     */
    static fromJSON = function(json_string){
        return ResponseError.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * Type or category of the error
 * @member {Object} type
 */
ResponseError.prototype['type'] = undefined;

/**
 * Detailed explanation of why the error occurred
 * @member {Object} reason
 */
ResponseError.prototype['reason'] = undefined;

/**
 * The index related to the error, if applicable
 * @member {Object} index
 */
ResponseError.prototype['index'] = undefined;


ResponseError.OneOf = ["ResponseErrorDetails", "String"];

export default ResponseError;

