/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SearchResponseHits from './SearchResponseHits';

/**
 * The SearchResponse model module.
 * @module model/SearchResponse
 * @version 6.0.0
 */
class SearchResponse {
    /**
     * Constructs a new <code>SearchResponse</code>.
     * Response object containing the results of a search request
     * @alias module:model/SearchResponse
     */
    constructor() { 
        
        SearchResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SearchResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SearchResponse} obj Optional instance to populate.
     * @return {module:model/SearchResponse} The populated <code>SearchResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SearchResponse();

            if (data.hasOwnProperty('took')) {
                obj['took'] = ApiClient.convertToType(data['took'], 'Number');
            }
            if (data.hasOwnProperty('timed_out')) {
                obj['timed_out'] = ApiClient.convertToType(data['timed_out'], 'Boolean');
            }
            if (data.hasOwnProperty('aggregations')) {
                obj['aggregations'] = ApiClient.convertToType(data['aggregations'], Object);
            }
            if (data.hasOwnProperty('hits')) {
                obj['hits'] = SearchResponseHits.constructFromObject(data['hits']);
            }
            if (data.hasOwnProperty('profile')) {
                obj['profile'] = ApiClient.convertToType(data['profile'], Object);
            }
            if (data.hasOwnProperty('scroll')) {
                obj['scroll'] = ApiClient.convertToType(data['scroll'], 'String');
            }
            if (data.hasOwnProperty('warning')) {
                obj['warning'] = ApiClient.convertToType(data['warning'], Object);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SearchResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SearchResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `hits`
        if (data['hits']) { // data not null
          SearchResponseHits.validateJSON(data['hits']);
        }
        // ensure the json data is a string
        if (data['scroll'] && !(typeof data['scroll'] === 'string' || data['scroll'] instanceof String)) {
            throw new Error("Expected the field `scroll` to be a primitive type in the JSON string but got " + data['scroll']);
        }

        return true;
    }


}



/**
 * Time taken to execute the search
 * @member {Number} took
 */
SearchResponse.prototype['took'] = undefined;

/**
 * Indicates whether the search operation timed out
 * @member {Boolean} timed_out
 */
SearchResponse.prototype['timed_out'] = undefined;

/**
 * Aggregated search results grouped by the specified criteria
 * @member {Object} aggregations
 */
SearchResponse.prototype['aggregations'] = undefined;

/**
 * @member {module:model/SearchResponseHits} hits
 */
SearchResponse.prototype['hits'] = undefined;

/**
 * Profile information about the search execution, if profiling is enabled
 * @member {Object} profile
 */
SearchResponse.prototype['profile'] = undefined;

/**
 * Scroll token to be used fo pagination
 * @member {String} scroll
 */
SearchResponse.prototype['scroll'] = undefined;

/**
 * Warnings encountered during the search operation
 * @member {Object} warning
 */
SearchResponse.prototype['warning'] = undefined;






export default SearchResponse;

