/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SourceRules model module.
 * @module model/SourceRules
 * @version 8.1.1
 */
class SourceRules {
    /**
     * Constructs a new <code>SourceRules</code>.
     * Defines which fields to include or exclude in the response for a search query
     * @alias module:model/SourceRules
     */
    constructor() { 
        
        SourceRules.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SourceRules</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SourceRules} obj Optional instance to populate.
     * @return {module:model/SourceRules} The populated <code>SourceRules</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SourceRules();

            if (data.hasOwnProperty('includes')) {
                obj['includes'] = ApiClient.convertToType(data['includes'], ['String']);
            }
            if (data.hasOwnProperty('excludes')) {
                obj['excludes'] = ApiClient.convertToType(data['excludes'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SourceRules</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SourceRules</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['includes'])) {
            throw new Error("Expected the field `includes` to be an array in the JSON data but got " + data['includes']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['excludes'])) {
            throw new Error("Expected the field `excludes` to be an array in the JSON data but got " + data['excludes']);
        }

        return true;
    }


}



/**
 * List of fields to include in the response
 * @member {Array.<String>} includes
 */
SourceRules.prototype['includes'] = undefined;

/**
 * List of fields to exclude from the response
 * @member {Array.<String>} excludes
 */
SourceRules.prototype['excludes'] = undefined;






export default SourceRules;
