/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SqlObjResponse model module.
 * @module model/SqlObjResponse
 * @version 9.0.0
 */
class SqlObjResponse {
    /**
     * Constructs a new <code>SqlObjResponse</code>.
     * @alias module:model/SqlObjResponse
     * @param hits {Object} 
     */
    constructor(hits) { 
        
        SqlObjResponse.initialize(this, hits);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hits) { 
        obj['hits'] = hits;
    }

    /**
     * Constructs a <code>SqlObjResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SqlObjResponse} obj Optional instance to populate.
     * @return {module:model/SqlObjResponse} The populated <code>SqlObjResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SqlObjResponse();

            if (data.hasOwnProperty('hits')) {
                obj['hits'] = ApiClient.convertToType(data['hits'], Object);
            }
            if (data.hasOwnProperty('took')) {
                obj['took'] = ApiClient.convertToType(data['took'], 'Number');
            }
            if (data.hasOwnProperty('timed_out')) {
                obj['timed_out'] = ApiClient.convertToType(data['timed_out'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SqlObjResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SqlObjResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SqlObjResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

SqlObjResponse.RequiredProperties = ["hits"];

/**
 * @member {Object} hits
 */
SqlObjResponse.prototype['hits'] = undefined;

/**
 * @member {Number} took
 */
SqlObjResponse.prototype['took'] = undefined;

/**
 * @member {Boolean} timed_out
 */
SqlObjResponse.prototype['timed_out'] = undefined;






export default SqlObjResponse;
