/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import QueryFilter from './QueryFilter';

/**
 * The UpdateDocumentRequest model module.
 * @module model/UpdateDocumentRequest
 * @version 10.0.0
 */
class UpdateDocumentRequest {
    /**
     * Constructs a new <code>UpdateDocumentRequest</code>.
     * Payload for updating a document or multiple documents in a table
     * @alias module:model/UpdateDocumentRequest
     * @param table {String} Name of the document table
     * @param doc {Object} Object containing the document fields to update
     */
    constructor(table, doc) { 
        
        UpdateDocumentRequest.initialize(this, table, doc);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, table, doc) { 
        obj['table'] = table;
        obj['doc'] = doc;
    }

    /**
     * Constructs a <code>UpdateDocumentRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateDocumentRequest} obj Optional instance to populate.
     * @return {module:model/UpdateDocumentRequest} The populated <code>UpdateDocumentRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateDocumentRequest();

            if (data.hasOwnProperty('table')) {
                obj['table'] = ApiClient.convertToType(data['table'], 'String');
            }
            if (data.hasOwnProperty('cluster')) {
                obj['cluster'] = ApiClient.convertToType(data['cluster'], 'String');
            }
            if (data.hasOwnProperty('doc')) {
                obj['doc'] = ApiClient.convertToType(data['doc'], Object);
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('query')) {
                obj['query'] = QueryFilter.constructFromObject(data['query']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateDocumentRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateDocumentRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateDocumentRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['table'] && !(typeof data['table'] === 'string' || data['table'] instanceof String)) {
            throw new Error("Expected the field `table` to be a primitive type in the JSON string but got " + data['table']);
        }
        // ensure the json data is a string
        if (data['cluster'] && !(typeof data['cluster'] === 'string' || data['cluster'] instanceof String)) {
            throw new Error("Expected the field `cluster` to be a primitive type in the JSON string but got " + data['cluster']);
        }
        // validate the optional field `query`
        if (data['query']) { // data not null
          QueryFilter.validateJSON(data['query']);
        }

        return true;
    }


}

UpdateDocumentRequest.RequiredProperties = ["table", "doc"];

/**
 * Name of the document table
 * @member {String} table
 */
UpdateDocumentRequest.prototype['table'] = undefined;

/**
 * Name of the document cluster
 * @member {String} cluster
 */
UpdateDocumentRequest.prototype['cluster'] = undefined;

/**
 * Object containing the document fields to update
 * @member {Object} doc
 */
UpdateDocumentRequest.prototype['doc'] = undefined;

/**
 * Document ID
 * @member {Number} id
 */
UpdateDocumentRequest.prototype['id'] = undefined;

/**
 * @member {module:model/QueryFilter} query
 */
UpdateDocumentRequest.prototype['query'] = undefined;






export default UpdateDocumentRequest;
