/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Manticoresearch);
  }
}(this, function(expect, Manticoresearch) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Manticoresearch.HitsHits();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('HitsHits', function() {
    it('should create an instance of HitsHits', function() {
      // uncomment below and update the code to test HitsHits
      //var instance = new Manticoresearch.HitsHits();
      //expect(instance).to.be.a(Manticoresearch.HitsHits);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new Manticoresearch.HitsHits();
      //expect(instance).to.be();
    });

    it('should have the property score (base name: "_score")', function() {
      // uncomment below and update the code to test the property score
      //var instance = new Manticoresearch.HitsHits();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "_source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new Manticoresearch.HitsHits();
      //expect(instance).to.be();
    });

    it('should have the property knnDist (base name: "_knn_dist")', function() {
      // uncomment below and update the code to test the property knnDist
      //var instance = new Manticoresearch.HitsHits();
      //expect(instance).to.be();
    });

    it('should have the property highlight (base name: "highlight")', function() {
      // uncomment below and update the code to test the property highlight
      //var instance = new Manticoresearch.HitsHits();
      //expect(instance).to.be();
    });

    it('should have the property table (base name: "table")', function() {
      // uncomment below and update the code to test the property table
      //var instance = new Manticoresearch.HitsHits();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "_type:")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Manticoresearch.HitsHits();
      //expect(instance).to.be();
    });

    it('should have the property fields (base name: "fields")', function() {
      // uncomment below and update the code to test the property fields
      //var instance = new Manticoresearch.HitsHits();
      //expect(instance).to.be();
    });

  });

}));
