/**
 * Manticore Search Client
 * Сlient for Manticore Search. 
 *
 * The version of the OpenAPI document: 5.0.0
 * Contact: info@manticoresearch.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AggComposite from './model/AggComposite';
import AggCompositeSource from './model/AggCompositeSource';
import AggCompositeTerm from './model/AggCompositeTerm';
import AggDateHistogram from './model/AggDateHistogram';
import AggHistogram from './model/AggHistogram';
import AggTerms from './model/AggTerms';
import Aggregation from './model/Aggregation';
import AutocompleteRequest from './model/AutocompleteRequest';
import BoolFilter from './model/BoolFilter';
import BulkResponse from './model/BulkResponse';
import DeleteDocumentRequest from './model/DeleteDocumentRequest';
import DeleteResponse from './model/DeleteResponse';
import ErrorResponse from './model/ErrorResponse';
import FulltextFilter from './model/FulltextFilter';
import GeoDistance from './model/GeoDistance';
import GeoDistanceLocationAnchor from './model/GeoDistanceLocationAnchor';
import Highlight from './model/Highlight';
import HighlightFieldOption from './model/HighlightFieldOption';
import HighlightFields from './model/HighlightFields';
import HitsHits from './model/HitsHits';
import InsertDocumentRequest from './model/InsertDocumentRequest';
import Join from './model/Join';
import JoinCond from './model/JoinCond';
import JoinOn from './model/JoinOn';
import Knn from './model/Knn';
import KnnQuery from './model/KnnQuery';
import Match from './model/Match';
import MatchAll from './model/MatchAll';
import PercolateRequest from './model/PercolateRequest';
import PercolateRequestQuery from './model/PercolateRequestQuery';
import QueryFilter from './model/QueryFilter';
import Range from './model/Range';
import ReplaceDocumentRequest from './model/ReplaceDocumentRequest';
import ResponseError from './model/ResponseError';
import ResponseErrorDetails from './model/ResponseErrorDetails';
import SearchQuery from './model/SearchQuery';
import SearchRequest from './model/SearchRequest';
import SearchResponse from './model/SearchResponse';
import SearchResponseHits from './model/SearchResponseHits';
import SourceRules from './model/SourceRules';
import SqlObjResponse from './model/SqlObjResponse';
import SqlResponse from './model/SqlResponse';
import SuccessResponse from './model/SuccessResponse';
import UpdateDocumentRequest from './model/UpdateDocumentRequest';
import UpdateResponse from './model/UpdateResponse';
import IndexApi from './api/IndexApi';
import SearchApi from './api/SearchApi';
import UtilsApi from './api/UtilsApi';


/**
* Сlient for Manticore Search. .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Manticoresearch = require('index'); // See note below*.
* var xxxSvc = new Manticoresearch.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Manticoresearch.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Manticoresearch.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Manticoresearch.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 8.1.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AggComposite model constructor.
     * @property {module:model/AggComposite}
     */
    AggComposite,

    /**
     * The AggCompositeSource model constructor.
     * @property {module:model/AggCompositeSource}
     */
    AggCompositeSource,

    /**
     * The AggCompositeTerm model constructor.
     * @property {module:model/AggCompositeTerm}
     */
    AggCompositeTerm,

    /**
     * The AggDateHistogram model constructor.
     * @property {module:model/AggDateHistogram}
     */
    AggDateHistogram,

    /**
     * The AggHistogram model constructor.
     * @property {module:model/AggHistogram}
     */
    AggHistogram,

    /**
     * The AggTerms model constructor.
     * @property {module:model/AggTerms}
     */
    AggTerms,

    /**
     * The Aggregation model constructor.
     * @property {module:model/Aggregation}
     */
    Aggregation,

    /**
     * The AutocompleteRequest model constructor.
     * @property {module:model/AutocompleteRequest}
     */
    AutocompleteRequest,

    /**
     * The BoolFilter model constructor.
     * @property {module:model/BoolFilter}
     */
    BoolFilter,

    /**
     * The BulkResponse model constructor.
     * @property {module:model/BulkResponse}
     */
    BulkResponse,

    /**
     * The DeleteDocumentRequest model constructor.
     * @property {module:model/DeleteDocumentRequest}
     */
    DeleteDocumentRequest,

    /**
     * The DeleteResponse model constructor.
     * @property {module:model/DeleteResponse}
     */
    DeleteResponse,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The FulltextFilter model constructor.
     * @property {module:model/FulltextFilter}
     */
    FulltextFilter,

    /**
     * The GeoDistance model constructor.
     * @property {module:model/GeoDistance}
     */
    GeoDistance,

    /**
     * The GeoDistanceLocationAnchor model constructor.
     * @property {module:model/GeoDistanceLocationAnchor}
     */
    GeoDistanceLocationAnchor,

    /**
     * The Highlight model constructor.
     * @property {module:model/Highlight}
     */
    Highlight,

    /**
     * The HighlightFieldOption model constructor.
     * @property {module:model/HighlightFieldOption}
     */
    HighlightFieldOption,

    /**
     * The HighlightFields model constructor.
     * @property {module:model/HighlightFields}
     */
    HighlightFields,

    /**
     * The HitsHits model constructor.
     * @property {module:model/HitsHits}
     */
    HitsHits,

    /**
     * The InsertDocumentRequest model constructor.
     * @property {module:model/InsertDocumentRequest}
     */
    InsertDocumentRequest,

    /**
     * The Join model constructor.
     * @property {module:model/Join}
     */
    Join,

    /**
     * The JoinCond model constructor.
     * @property {module:model/JoinCond}
     */
    JoinCond,

    /**
     * The JoinOn model constructor.
     * @property {module:model/JoinOn}
     */
    JoinOn,

    /**
     * The Knn model constructor.
     * @property {module:model/Knn}
     */
    Knn,

    /**
     * The KnnQuery model constructor.
     * @property {module:model/KnnQuery}
     */
    KnnQuery,

    /**
     * The Match model constructor.
     * @property {module:model/Match}
     */
    Match,

    /**
     * The MatchAll model constructor.
     * @property {module:model/MatchAll}
     */
    MatchAll,

    /**
     * The PercolateRequest model constructor.
     * @property {module:model/PercolateRequest}
     */
    PercolateRequest,

    /**
     * The PercolateRequestQuery model constructor.
     * @property {module:model/PercolateRequestQuery}
     */
    PercolateRequestQuery,

    /**
     * The QueryFilter model constructor.
     * @property {module:model/QueryFilter}
     */
    QueryFilter,

    /**
     * The Range model constructor.
     * @property {module:model/Range}
     */
    Range,

    /**
     * The ReplaceDocumentRequest model constructor.
     * @property {module:model/ReplaceDocumentRequest}
     */
    ReplaceDocumentRequest,

    /**
     * The ResponseError model constructor.
     * @property {module:model/ResponseError}
     */
    ResponseError,

    /**
     * The ResponseErrorDetails model constructor.
     * @property {module:model/ResponseErrorDetails}
     */
    ResponseErrorDetails,

    /**
     * The SearchQuery model constructor.
     * @property {module:model/SearchQuery}
     */
    SearchQuery,

    /**
     * The SearchRequest model constructor.
     * @property {module:model/SearchRequest}
     */
    SearchRequest,

    /**
     * The SearchResponse model constructor.
     * @property {module:model/SearchResponse}
     */
    SearchResponse,

    /**
     * The SearchResponseHits model constructor.
     * @property {module:model/SearchResponseHits}
     */
    SearchResponseHits,

    /**
     * The SourceRules model constructor.
     * @property {module:model/SourceRules}
     */
    SourceRules,

    /**
     * The SqlObjResponse model constructor.
     * @property {module:model/SqlObjResponse}
     */
    SqlObjResponse,

    /**
     * The SqlResponse model constructor.
     * @property {module:model/SqlResponse}
     */
    SqlResponse,

    /**
     * The SuccessResponse model constructor.
     * @property {module:model/SuccessResponse}
     */
    SuccessResponse,

    /**
     * The UpdateDocumentRequest model constructor.
     * @property {module:model/UpdateDocumentRequest}
     */
    UpdateDocumentRequest,

    /**
     * The UpdateResponse model constructor.
     * @property {module:model/UpdateResponse}
     */
    UpdateResponse,

    /**
    * The IndexApi service constructor.
    * @property {module:api/IndexApi}
    */
    IndexApi,

    /**
    * The SearchApi service constructor.
    * @property {module:api/SearchApi}
    */
    SearchApi,

    /**
    * The UtilsApi service constructor.
    * @property {module:api/UtilsApi}
    */
    UtilsApi
};
